services:
    frontend:
        container_name: slothsoft_frontend
        build:
            context: .
            args:
                PHP_VERSION: ${PHP_VERSION}
        secrets:
            - mysql_password
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
        volumes:
            - slothsoft_data:/var/www/data
        networks:
            - vhosts
            - mysql
        expose:
            - 80
        labels:
            - "com.github.nginxproxy.nginx-proxy.expose=true"
            - "VIRTUAL_HOST=slothsoft.net"
            - "LETSENCRYPT_HOST=slothsoft.net"
        restart: unless-stopped

volumes:
    slothsoft_data:
        external: true

networks:
    vhosts:
        external: true
    mysql:
        external: true

secrets:
    mysql_password:
        file: /var/secrets/mysql_password