services:
    slothsoft:
        image: faulo/farah:7.4
        secrets:
            - mysql_password
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
        volumes:
            - .:/var/www
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        networks:
            - vhosts_default
            - mysql_default

networks:
    vhosts_default:
        external: true
    mysql_default:
        external: true

secrets:
    mysql_password:
        external: true