services:
    frontend:
        build:
            context: .
        secrets:
            - mysql_password
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
        volumes:
            - data:/var/www/data
        networks:
            - vhosts
            - mysql
        restart: unless-stopped

volumes:
    data:

networks:
    vhosts:
        external: true
    mysql:
        external: true

secrets:
    mysql_password:
        file: /var/secrets/mysql_password