services:
    frontend:
        container_name: ${STACK_NAME}_frontend
        build:
            dockerfile: Dockerfile.linux
            args:
                PHP_VERSION: ${PHP_VERSION}
        secrets:
            - mysql_password
        environment:
            SERVER_NAME: ${SERVER_NAME}
            VIRTUAL_HOST: ${SERVER_NAME}
            LETSENCRYPT_HOST: ${SERVER_NAME}
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
        volumes:
            - /var/vhosts/${SERVER_NAME}/:/var/www/data/
        tmpfs:
            - /var/www/cache/:uid=33,gid=33
        networks:
            - vhosts
            - mysql
        expose:
            - 80
        restart: unless-stopped

volumes:
    slothsoft_data:
        external: true

networks:
    vhosts:
        external: true
    mysql:
        external: true

secrets:
    mysql_password:
        file: /var/secrets/mysql_password