COPY --from=farah /usr/share/farah/ /usr/share/farah/
COPY --from=farah /etc/apache2/conf-available/custom.conf /etc/apache2/conf-enabled/farah.conf

RUN sed -i \
        '/$request = MessageFactory::createServerRequest/i $_SERVER["HTTPS"] = "off";\n$_SERVER["REQUEST_SCHEME"] = "http";' \
        /usr/share/farah/index.php
