services:
    frontend:
        image: tmp/${STACK_NAME}:latest
        secrets:
            - mysql_password
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_password
        volumes:
            - data:/var/www/data
        networks:
            - vhosts_default
            - mysql_default
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s

volumes:
    data:

networks:
    vhosts_default:
        external: true
    mysql_default:
        external: true

secrets:
    mysql_password:
        external: true